export const watermarkPlacementPrompt = (
  imgWidth: number,
  imgHeight: number,
  wmWidth: number,
  wmHeight: number,
) => [
  `You are analyzing an image to determine the best placement and size for a watermark.`,
  `The image is ${imgWidth}x${imgHeight} pixels. The watermark at native size is ${wmWidth}x${wmHeight} pixels.`,
  ``,
  `Choose:`,
  `- (x, y): TOP-LEFT corner of the watermark in pixels`,
  `- scale: a multiplier to resize the watermark (e.g. 1.0 = native size, 0.5 = half size)`,
  ``,
  `Follow these placement rules exactly:`,
  ``,
  `CORE PRINCIPLE: Place the watermark exclusively on clear, visually simple background area — table surface, placemat, box lining, satin, plain backdrop, or blank packaging. Never place over the main subject's decorative surfaces, painted/printed patterns, fine texture, characters, faces, or text printed on the item. This constraint overrides all positional rules below.`,
  ``,
  `DECISION LOGIC (apply in order):`,
  `1. Is the lower-left region clear of the main subject?`,
  `   YES → place at x: 3–8% from left (${Math.round(imgWidth * 0.03)}–${Math.round(imgWidth * 0.08)} px), y: 65–88% from top (${Math.round(imgHeight * 0.65)}–${Math.round(imgHeight * 0.88)} px).`,
  `   NO  → Is the lower-right region clear?`,
  `         YES → place at x: 60–80% from left (${Math.round(imgWidth * 0.6)}–${Math.round(imgWidth * 0.8)} px), y: 65–88% from top (${Math.round(imgHeight * 0.65)}–${Math.round(imgHeight * 0.88)} px).`,
  `         NO  → Find the largest open background patch anywhere in the image and place there, preferring the left side over right if equal.`,
  ``,
  `VERTICAL ADAPTATION: If neither the lower-left nor lower-right has clear background (e.g. close-up shots where the subject fills most of the frame), place at whatever vertical position the nearest open background patch occupies. Do not force a lower position if it would overlap the subject.`,
  ``,
  `PACKAGING EXCEPTION: If product boxes, booklets, paper inserts, or warranty cards are visible in the image, the watermark may be placed on top of those elements in the lower portion — provided it does not obscure critical text on the item itself.`,
  ``,
  `SIZE: Scale the watermark so its width is 15–20% of the image width. Target width: ${Math.round(imgWidth * 0.18)} px. Compute scale: target_scale = ${Math.round(imgWidth * 0.18)} / ${wmWidth}.`,
  ``,
  `EDGE INSET: Maintain at least 3–5% margin from all four edges. The watermark must never be cropped.`,
  ``,
  `NO ROTATION: Place horizontally at 0° always.`,
  ``,
  `OPACITY: The watermark should always appear subtle. Choose a value between 0.35 and 0.65.`,
  `- Use 0.35–0.45 when the background is light (cream, white, light blue, pale satin).`,
  `- Use 0.45–0.55 when the background is mid-tone (light brown tablecloth, warm beige, light grey).`,
  `- Use 0.55–0.65 when the background is dark (dark brown/chocolate placemat, black satin, dark backdrop).`,
  `Never exceed 0.65 — the watermark is always understated.`,
  ``,
  `Respond with x, y, scale, opacity, and a brief justification.`,
].join("\n");
